project:
  type: website

website:
  title: "Ayush Thakur"
  site-url: "https://ayusht.dev"
  description: "Engineer, writer, thinker."
  navbar:
    background: light
    search: false
    left:
      - href: about.qmd
        text: About
      - href: blog/index.qmd
        text: Writing
    right:
      - icon: github
        href: https://github.com/ayulockin
        aria-label: GitHub
      - icon: twitter
        href: https://x.com/ayushthakur0
        aria-label: Twitter
      - icon: linkedin
        href: https://www.linkedin.com/in/ayush-thakur-731914149/
        aria-label: LinkedIn
  page-footer:
    center: 
      - text: "Â© 2025 Ayush Thakur"

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: false
    highlight-style: github
    fontsize: 18px
    linestretch: 1.7
